# Generated by Django 5.2.11 on 2026-02-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_application_cover_letter_application_status'),
        ('tasks', '0004_application_cover_letter_application_status'),
    ]

    operations = [
    ]
